### PR TITLE
Add description of DR10.1 photometric redshift catalog to the files page

### PR DESCRIPTION
**Pull request by geordie666**
This PR adds documentation of Rongpu's DR10.1 photoz catalog to the DR10 files page. It also:

  - Activates the Zhou et al. (2023) photoz paper links to point to the arXiv version of the publication.
  - Updates the DR10.1 documentation and the `RELEASE` table to include the new `RELEASE=10002` number.
  - Adds a mention of DR10.1 to the landing page.

### CODE REVIEW

**Comment by geordie666** [comment]
The compiled version of the pages can be viewed [here](https://data.desi.lbl.gov/desi/users/adamyers/output/)

**Comment by rongpu** [comment]
@geordie666 Thanks! This looks good overall. I just have two suggestions:
1) We also use WISE W1 and W2 for the photo-z's. So it would be more accurate to say that the photo-z's are based on grzW1W2 or grizW1W2 fluxes. Or maybe there is a better way to describe this?
2) I think it would be useful to include the table of the performance numbers (https://portal.nersc.gov/project/cosmo/temp/rongpu/dr10/pz/dr10_photoz_performance.txt). We can simply include the link to the .txt file and say that the numbers are defined in (or can be compared to) Table 7 of [Zhou et. al 2023](https://ui.adsabs.harvard.edu/abs/2023arXiv230906443Z/abstract).

**Comment by geordie666** [comment]
@rongpu: I think I addressed both your comments. Please take a look at the [new version](https://data.desi.lbl.gov/desi/users/adamyers/output/dr10/files/#photo-z-sweeps-10-1-photo-z-sweep-brickmin-brickmax-pz-fits).

**Comment by rongpu** [comment]
Just one typo: i-bad -> i-band. Otherwise looks good!

**Comment by geordie666** [comment]
Oops, thanks for catching that unfortunate typo.

@weaverba137: If we merge this soon will you have time to serve a new version of the web pages in the next day or so?

**Comment by weaverba137** [comment]
Yes, definitely.

**Comment by geordie666** [comment]
OK, merging now @weaverba137. Feel free to tag-and-serve when ready.

**Pull request merged**
