### PR TITLE
Dr3.1fixes

### PR DESCRIPTION
**Pull request by geordie666**

### CODE REVIEW

**Comment by weaverba137** [comment]
Hang on, did you actually address any of the comments?

**Comment by geordie666** [comment]
which comments? I don't see any on git and I haven't received any over email?

**Comment by weaverba137** [comment]
Ugh, I didn't hit 'submit review'.

**Comment by geordie666** [comment]
Again, apologies if I merged the PR too fast, but I'm happy to back out changes if @weaverba137 points me to the comments?

**Comment by weaverba137** [comment]
Check again.

**Comment by weaverba137** [comment]
On this PR.

**Comment by weaverba137** [comment]
But yes, that was WAY to fast a merge.

**Comment by geordie666** [comment]
OK, I see the comments now. Instead of reverting I'll spawn a new branch off master and fix your comments in that new branch. This one got messy.

**Comment by weaverba137** [comment]
OK

**Pull request merged**
