### PR TITLE
Update Gallery URL and other fixes.

### PR DESCRIPTION
**Pull request by weaverba137**
* Update base URL so that navbar links work (*e.g.* http://legacysurvey.org/contacts -> http://legacysurvey.org/test/contacts).  This will have to be changed back when DR2 is ready to go live.
* Eliminate built-in gallery and link to gallery at NERSC instead.
* Update link to source code on GitHub.
* Clean up Acknowledgements section on front page.
* Add sizes of all subdirectories.

### CODE REVIEW

**Comment by moustakas** [comment]
Let's be sure someone ( @geordie666 @djschlegel ?) merges this PR before we go live!

**Comment by weaverba137** [comment]
Thanx, @geordie666!

Don't forget, you'll still have to change legacysurvey.org/test to legacysurvey.org before going live!

**Comment by geordie666** [comment]
I merged it, although we should remember to change legacysurvey.org to legacysurvey.org/test before the data release.

**Comment by weaverba137** [comment]
**NO** you've got it the wrong way around!

**Comment by geordie666** [comment]
typo, sorry!

**Comment by weaverba137** [comment]
Great, @djschlegel went ahead and deployed without paying attention to this.

**Pull request merged**
