### PR TITLE
Document SUB_BLOB problem as a known issue for DR10

### PR DESCRIPTION
**Pull request by geordie666**
This PR extends the DR10 known issues page to describe missing sources due to `SUB_BLOB` processing.

A rendering of the result is available [here](https://data.desi.lbl.gov/desi/users/adamyers/output/dr10/issues/#bricks-for-which-sub-blob-was-set).

In addition, I updated the changes file to document PR #168.

### CODE REVIEW

**Comment by geordie666** [comment]
@weaverba137: Can we merge this PR and #168 at some point and serve the new version of the pages? I don't think this is particularly urgent, but this PR will keep popping up in David's weekly email as "Add to docs the list of bricks with SUB_BLOB set, and potentially dropped sources."

Note that I updated the changes docs for #168 in _this_ PR, so I don't think there will be any merge conflicts.

**Comment by weaverba137** [comment]
Be sure to tag me as a reviewer next time because I wasn't aware of this PR. Go ahead and merge, & I'll deploy probably later today.

**Comment by weaverba137** [comment]
PS, are you planning to merge both this PR & #168?

**Comment by geordie666** [comment]
@weaverba137: OK, everything is merged. Deploy at your leisure.

**Pull request merged**
