### PR TITLE
Support latest Nikola version

### LINKED ISSUE #90: Ensure that the "custom" theme is supported by recent versions of Nikola.
With Nikola v8.0.2, `nikola build` warns:
```
[2019-07-05T19:59:03Z] WARNING: Nikola: Cannot load theme "custom", using 'bootblog4' instead.
```
And the pages do not look like our standard legacysurvey.org theme.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR closes #90.

This update is compatible with the latest Nikola version, 8.2.2.

I've done my best to not change the appearance or content, but you might notice small differences in table formatting.  For the better, I think.

@geordie666, @dstndstn, could you please test by building this branch with the latest version of Nikola and checking that everything looks like the current website?

### CODE REVIEW

**Comment by geordie666** [comment]
Oops, yes, you're correct — thanks. I was focused on installing the latest version of nikola and forgot to switch to the `nikola8` branch.

https://data.desi.lbl.gov/desi/users/adamyers/output/ looks much better, now. I'll review it when I find some time (I'm currently at the DESI-II meeting).

**Comment by weaverba137** [comment]
Good, that's fine, this is not urgent.

**Comment by geordie666** [comment]
@weaverba137: I built the site (https://data.desi.lbl.gov/desi/users/adamyers/output/) and carefully went through the content.

Everything looks ostensibly the same to me. There are a few minor differences — but nothing that looks bad. I'm happy for you to merge this PR whenever you're ready.

**Review by geordie666 — APPROVED** [review]

**Comment by weaverba137** [comment]
@dstndstn, do you want to give this a try?  I'd like to make sure that multiple people can build with the latest version.

**Comment by dstndstn** [comment]
I was able to update to the newest nikola, check out the nikola8 branch, build and serve, and it looked fine!

**Pull request merged**
