### PR TITLE
Fix minor typos in psfdepth description on catalogs page

### PR DESCRIPTION
**Pull request by geordie666**
This PR fixes g/r/z description typos on the catalogs pages for every Data Release. These are minor updates, so this PR can be merged at any time.

### CODE REVIEW

**Comment by weaverba137** [comment]
@geordie666, could you merge this after @moustakas merges #137?  Double-check that there are no conflicts first though, & merge with master if necessary.

**Comment by geordie666** [comment]
@weaverba137: I've resolved conflicts, I'll merge once tests pass (in, maybe, 10 minutes).

**Comment by geordie666** [comment]
@weaverba137: I've just noticed that there's a broken link in the changes file (introduced in #138) due to an unnecessary extra closing parenthesis after `PR#138]`:

([PR#138])(https://github.com/legacysurvey/legacysurvey/pull/138))

I could fix that in this branch if you'd like, but it's probably easiest just to fix it when you make a tag? Your call.

**Comment by weaverba137** [comment]
@geordie666, please fix this on the branch.

**Comment by geordie666** [comment]
Done. I'll merge in 10 minutes, unless somebody beats me to it.

**Pull request merged**
