### PR TITLE
Updates for DR8 website.

### PR DESCRIPTION
**Pull request by geordie666**
Includes:
- Latest data model.
    - In particular, partition directories by north/south.
    - New files added to the random catalogs.
- General language describing how MzLS/BASS/DECaLS are merged into a single release.
- New pages, including:
    - Updates (major changes in scope since DR7).
    - External catalogs (decription and locations of catalogs used for masking/astrometry/photometry).
    - Bitmasks (the data model for all of the masks in DR8).
- Updates for publications through June, 2019.
- Sharper depth histograms.
- Contents side bars on most pages.
- Addresses #86, #87 and #88.

### CODE REVIEW

**Comment by geordie666** [comment]
@weaverba137: @mlandriau is almost finished putting the final DR8 directory in place for you to link. Here is the DR8 website.

Normally, I'd ask you for a careful review. In this case, as there's some urgency in pushing this before the July 8th "drop-dead" release date, I'm hoping that you can let any minor errors on my part slide. If there's something serious that I simply _have_ to address, let me know and I'll try to fix things ASAP tomorrow morning. If there are minor items that you can handle, feel free just to add to this PR or spin off your own.

Let's open an issue (with a set of corrections) for anything that should be addressed but that you're willing to let slide, and I'll deal with those corrections after (or during) the collaboration meeting. One thing we'll need to open an issue about is the status plots. We don't have the DR8 versions yet, so I've left the DR7 plots in place and included language that the DR8 status plots are "coming soon."

Thanks, as always.

**Comment by weaverba137** [comment]
@geordie666, understood.  I'll get this merged soon.

**Comment by weaverba137** [comment]
@geordie666, PS, is there a more specific time to get this out to the public besides before the start of the meeting on the 8th?

**Comment by geordie666** [comment]
@weaverba137: That would be a question for @djschlegel to answer. I know there's a press release on the 8th, but I don't know if there's an exact time-of-day for that press release.

**Comment by geordie666** [comment]
@weaverba137: I just found the "living" press release and the current date of release states:

EMBARGOED - Until 8 a.m. Pacific Time on Monday, July 8, 2019.

**Comment by weaverba137** [comment]
Good, thank you.  I think we'll be live well before that.

**Pull request merged**
