### PR TITLE
Fix typo in formulae for how to convert depths to magnitude

### PR DESCRIPTION
**Pull request by geordie666**
@kaylanb noticed that the parentheses were in the wrong place for all of the depth-to-magnitude equations. This PR should fix that for all data releases.

### CODE REVIEW

**Comment by geordie666** [comment]
I added some extra options to the cutout server description for DR5 and DR6 as requested by Steve Willner [here](https://groups.google.com/forum/#!topic/decam-legacy-survey/VsQKTpUKGkM)

**Comment by geordie666** [comment]
I originally requested a review from @kaylanb, but he's understandably busy at the moment. If @weaverba137 could review and push the changes to the legacysurvey.org website, that'd be excellent.

**Comment by weaverba137** [comment]
I actually have to leave for the day right now.  At a quick glance this looks good.  I might be able to deploy this tomorrow, or Monday at the latest.

**Comment by geordie666** [comment]
Yep, no urgency on this whatsoever. Thanks @weaverba137.

**Comment by weaverba137** [comment]
Took a second look, and all looks fine.  I'm going to merge, & hopefully install today.

**Pull request merged**
