### PR TITLE
[WIP] NOIRLab.edu migration

### PR DESCRIPTION
**Pull request by dstndstn**
- update email addresses and some URLs from noao.edu to noirlab.edu

Still to do:

- I only updated the DR9 pages!
- I can't find anything on the new NOIRLab web page, so I did not update many of the links to, eg, DECam instrument information.
- Does the FTP interface to the NOAO Archive still work?

### CODE REVIEW

**Comment by dstndstn** [comment]
(note, I am not going to do anything more on this ticket because I'm not even NOIRLab affiliated, but thought I'd do the easy/important bits)

**Comment by weaverba137** [comment]
@dstndstn, are you still waiting for feedback from NOIRLab personnel on this?  Or is there another reason this is stalled?

**Comment by dstndstn** [comment]
We could merge this now -- it's an improvement, but not complete.

**Comment by weaverba137** [comment]
Then let's wait until you're satisfied that it's complete.  I was just wondering why no NOIRLab individuals had been tagged as reviewers.

**Comment by dstndstn** [comment]
If @ameisner or @stephjuneau or @arjundey have time maybe they can take a look.
I know you're all busy so feel free to pass.

**Comment by weaverba137** [comment]
Here's a big piece that's missing: we need to replace all instances of the NOAO Logo with the NOIRLab logos.  The expectation is that the NSF logo should be the same size as the NOIRLab logo, just like on https://noirlab.edu.  I would *not* merge this until that is done at minimum.

We should probably update *all* of the ftp links, since most browsers are now dropping support for ftp altogether.

**Comment by weaverba137** [comment]
PS, I'm actively working on these topics.

**Comment by weaverba137** [comment]
OK, so almost all of the URLs that begin with `ftp:` are actually *invalid* and should be *removed*.

For example in `dr9/files.rst`:
```rst
- Raw: ftp://archive.noao.edu/public/hlsp/ls/dr9/raw/``<AAA>/<brick>``
- Calibrated: ftp://archive.noao.edu/public/hlsp/ls/dr9/calibrated/``<AAA>/<brick>``
- Stacked: ftp://archive.noao.edu/public/hlsp/ls/dr9/coadd/``<AAA>/<brick>``
```

We no longer create the "Raw" or "Calibrated" paths, and have not done so since like DR4 or DR5.
The "Stacked" URL is also bad because the coadd files are in the north/south directories.

I recommend removing all references to FTP access in all data releases.

**Comment by weaverba137** [comment]
Well, this is a bit of a rabbit hole, but it's now clear that *all* instructions for obtaining raw and CP data from NOIRLab need to be updated.  I'm working with NOIRLab to update the web interface instructions, but we should plan to eliminate the ftp section entirely, and rewrite the naming convention paragraphs that are part of that section.

**Comment by dstndstn** [comment]
Thank you for all this, @weaverba137

**Comment by moustakas** [comment]
BTW, while I'm thinking about it, once this PR is merged it would be good to update the main branch from `master` to `main`.

**Comment by weaverba137** [comment]
@moustakas, yes I was planning on that.

**Comment by weaverba137** [comment]
I propose merging this now to get in the majority of changes prior to the SGA announcement.

The main remaining item is to update the raw data download instructions for the new NOIRLab archive. That may take a while anyway, so it can be a separate PR.

**Comment by weaverba137** [comment]
Last call, merging momentarily.

**Pull request merged**
