### PR TITLE
fix incorrect links to the SGA

### PR DESCRIPTION
**Pull request by moustakas**
I neglected to update all the links to the updated SGA documentation in my previous PRs.

### CODE REVIEW

**Comment by moustakas** [comment]
@geordie666 @weaverba137 any objections to merging this PR and then tagging and re-deploying the website? I've fixed broken links here so these changes should be non-controversial.

**Comment by weaverba137** [comment]
This is fine, but please update the `CHANGES.md` file.

**Comment by moustakas** [comment]
> This is fine, but please update the CHANGES.md file.

Blarg, I forgot. Done.

**Comment by weaverba137** [comment]
OK, I can deploy this shortly if you're fully ready to merge.

**Comment by moustakas** [comment]
Yes, this is ready to go on my end. I'm fairly confident I fixed all the links I missed previously.

**Pull request merged**
