### PR TITLE
Add documentation of photo-z files

### PR DESCRIPTION
**Pull request by weaverba137**
This PR adds documentation of the photometric redshift files.

@geordie666, could you set up this branch on your legacysurvey.org test site?

### CODE REVIEW

**Comment by geordie666** [comment]
@weaverba137: This looks good to me. See:

http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/dr8/files/#photometric-redshift-files-8-0-photo-z-sweep-brickmin-brickmax-pz-fits

There is a statement:

```
Details of the photo-z training and performance can be found in arXiv:xxxx.xxxx.
```

Do we want to wait until we have the arXiv link to merge this? Or just assume that we'll make another update once the paper is posted?

**Comment by weaverba137** [comment]
Yes, I think we should wait until the arXiv link is available.

**Comment by janewman-pitt-edu** [comment]
I'd like us to change the documentation a bit to request that users of this catalog
a) cite Rongpu's paper
and 
b) acknowledge the DOE funding which produced the catalog.  

What would be the best way to implement this change?

**Comment by weaverba137** [comment]
Good question.  I assume that the acknowledgement would be in addition to the existing Legacy Survey acknowledgement: http://legacysurvey.org/acknowledgment/.

I think we can include a paragraph mentioning that in the description of the files. But are there other places we should mention this?

**Comment by janewman-pitt-edu** [comment]
I think putting it both places would be good.
I.e.: 1) where the catalog is introduced, say that papers using it should cite Rongpu and include the acknowledgement
and
2) where acknowledgements are listed, at the end say that papers that use the photo-z catalog should additionally add the photo-z acknowledgment (I need to dig up the grant # to write it).

**Comment by weaverba137** [comment]
That sounds good.

**Comment by weaverba137** [comment]
Note to self: check data volume table.

**Comment by weaverba137** [comment]
Data volume table has been updated.  Still to do before merging:

- [ ] arXiv link
- [ ] Citation and acknowledgement

**Comment by rongpu** [comment]
@weaverba137: Is it possible to trim down the url for the photo-z's? Currently it's [http://legacysurvey.org/dr8/files/#photometric-redshift-files-8-0-photo-z-sweep-brickmin-brickmax-pz-fits](url), which is too long to fit in one line in a two-column PDF.
Maybe something like [http://legacysurvey.org/dr8/files/#photometric-redshifts](url)?

**Comment by weaverba137** [comment]
@rongpu, I think this is possible in RST.  I'll have to run some tests.

**Comment by weaverba137** [comment]
OK, cross-reference added and working.  You should be able to use `.../dr8/files/#photometric-redshifts`, once this is merged and installed.

**Comment by weaverba137** [comment]
@janewman-pitt-edu, did you ever find the DOE grant information for the acknowledgement?

**Comment by rongpu** [comment]
@weaverba137 The DOE grant is DE-SC0007914.

**Comment by weaverba137** [comment]
Thank you, but could you please provide the full acknowledgement in paragraph form?

**Comment by weaverba137** [comment]
Also, since the holidays are coming up, is the paper likely to be ready before or after the holidays?

**Comment by rongpu** [comment]
@weaverba137: could you add the following as the last paragraph:

> Work which uses this photometric redshift catalog should cite Zhou et al. 2020 and include the following acknowledgment: "The Photometric Redshifts for the Legacy Surveys (PRLS) catalog used in this paper was produced thanks to funding from the U.S. Department of Energy Office of Science, Office of High Energy Physics via grant DE-SC0007914."

And could you also change the first sentence/paragraph to this (to introduce the acronym):

> The Photometric Redshifts for the Legacy Surveys (PRLS, Zhou et al. 2020 (arxiv_link_here)) catalog is line-matched to the DR8 sweep catalogs as described above.

I think we will submit the paper after the holidays.

**Comment by weaverba137** [comment]
@rongpu, that looks fine, but when you say "last paragraph" or "first sentence", which sections on which page(s) are you referring to?

**Comment by rongpu** [comment]
Sorry, I'm referring to the photo-z section (http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/dr8/files/#photometric-redshift-files-8-0-photo-z-sweep-brickmin-brickmax-pz-fits), i.e. the current "first sentence" is "The photometric redshift (photo-z) catalogs are line-matched..."

**Comment by weaverba137** [comment]
OK thank you.  Note also that we need to add an acknowledgement *separately* to the acknowledgements page, as Jeff had discussed.

**Comment by weaverba137** [comment]
I think I've got everything in the right place, and there is a single placeholder for the arXiv link when it appears.  @geordie666 , could you update your test page when you get a chance?

**Comment by geordie666** [comment]
@weaverba137: I've updated the [test page](http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/). The new acknowledgment, specifically, is on [the acknowledgments page](http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/acknowledgment/).

**Comment by weaverba137** [comment]
Looks good, thank you!

**Comment by weaverba137** [comment]
Last call for comments on this!  The Paper is out on arXiv, so this needs to go live soon.

**Pull request merged**
