### PR TITLE
Continuing minor updates

### PR DESCRIPTION
**Pull request by geordie666**
This PR addresses the slate of update requests listed in issue #170. 

I'll leave this open for now as in the next week or so we'll likely want to also add a citation or two to John's SGA-2020 paper before serving a new version of the website.

### CODE REVIEW

**Comment by moustakas** [comment]
@geordie666 I would like to update the SGA-2020 documentation to match the (imminently to-be-submitted) paper. Should I do this here, in this PR, or in a separate one?

**Comment by geordie666** [comment]
Let's make the SGA updates in _this_ PR. Then Ben can check-and-serve everything at the same time.

**Comment by geordie666** [comment]
The latest version of the pages with the latest slate of changes is [here](https://data.desi.lbl.gov/desi/users/adamyers/output/).

**Comment by moustakas** [comment]
I'm working on reconciling the SGA documentation with the submitted SGA-2020 paper and I have a question for the group. The current (previous / original) documentation is here
https://www.legacysurvey.org/sga/sga2020/
and the submitted paper is here:
https://arxiv.org/pdf/2307.04888.pdf

Should I take out most of the text in the documentation and simply point to the relevant parts of the paper? Or is there another model I'm not thinking of that doesn't involve reproducing the text of the paper as documentation? Maybe focusing on the data model, known issues, and a few key figures is the way to go?

Thanks in advance for any thoughts and feedback.

**Comment by geordie666** [comment]
I think the data model is the most crucial element for the webpages. So maybe just a little introductory paragraph and the data model, with all other elements redirected to the SGA paper?

If there are known issues that are _not_ in the paper, then you should certainly add those.

**Comment by stephjuneau** [comment]
Hi John, I think the method, etc. can all refer to the paper but it would be useful to say what kind of info is found in which section with either a list of bullets or a short paragraph similar to the usual "This paper is organized as follows..." description.   From the sections headings, you could shorten the "Overview" and add the suggested content above, and then keep "Data Products", "Known Issues" (as those could be updated after the paper is published), "Feedback", "Future Plans", "Acknowledgments"

**Comment by geordie666** [comment]
@weaverba137: I'd like to merge this PR so you can serve this version of the webpages. 

The reason is that @rongpu's photo-z paper will be submitted in the next couple of weeks and the documentation for the new photo-z files is included in this PR. 

@moustakas has signed off on working on his SGA updates in a separate branch.

On the other hand, I will also want to make new updates to describe DR10.1. So maybe we merge this PR but you can hold off about a week to serve the pages?

**Comment by weaverba137** [comment]
The content all looks fine.  Let me double-check that I can independently compile it.

**Comment by weaverba137** [comment]
Compiles fine for me.  I vote for holding off on deploying until there are additional changes.

**Comment by weaverba137** [comment]
So merge when ready.

**Pull request merged**
