### PR TITLE
Further updates for DR7 documentation

### PR DESCRIPTION
**Pull request by geordie666**
A few additional updates for DR7.

### CODE REVIEW

**Comment by geordie666** [comment]
@weaverba137: If these changes look good and we have no more requests to the list by "end of day" please merge.

**Comment by weaverba137** [comment]
Will do.

**Comment by moustakas** [comment]
I suck! Let's just merge and announce. My comments are all trivial and can
be pushed to DR8.

**Comment by weaverba137** [comment]
@moustakas, could you turn your comments into a GitHub issue so we don't forget?

**Pull request merged**
